import type { DesignConfig } from "./types";

/** The default design system shown when the app first loads. */
export const defaultConfig: DesignConfig = {
  meta: {
    name: "Acme Design System",
    version: "1.0.0",
    description: "A starter design system generated by DesignSync Studio.",
    targetStack: "react-tailwind",
    componentLib: "none",
  },
  theme: {
    mode: "light",
    style: "modern",
    colors: {
      primary: "#2563eb",
      secondary: "#7c3aed",
      accent: "#f59e0b",
      neutral: "#64748b",
      success: "#16a34a",
      warning: "#d97706",
      error: "#dc2626",
      info: "#0ea5e9",
    },
  },
  typography: {
    fontFamilyBase: "Inter, sans-serif",
    fontFamilyHeading: "Inter, sans-serif",
    fontFamilyMono: "JetBrains Mono, monospace",
    baseSize: 16,
    scaleRatio: 1.25,
    weights: [400, 500, 600, 700],
    lineHeight: 1.5,
  },
  spacing: {
    baseUnit: 4,
    scale: [0, 1, 2, 3, 4, 6, 8, 12, 16, 24],
  },
  radius: {
    style: "rounded",
    base: 8,
  },
  borders: {
    width: 1,
    style: "solid",
    defaultColorToken: "neutral-200",
  },
  elevation: {
    style: "soft",
    levels: 4,
  },
  animation: {
    enabled: true,
    style: "smooth",
    durationMs: 200,
    easing: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  interactions: {
    hover: "darken",
    pressFeedback: true,
    focusRing: true,
    underlineLinks: true,
  },
  components: {
    button: { variants: ["primary", "secondary", "ghost", "destructive"], defaultSize: "md" },
    input: { variant: "outline" },
    card: { variant: "elevated" },
    badge: { enabled: true },
    modal: { enabled: true },
    table: { enabled: true },
  },
  aiRules: {
    enforceTokensOnly: true,
    namingConvention: "tailwind",
    accessibility: "AA",
    cleanCode: true,
    customRules: [],
  },
};

/** Deep clone helper so callers never mutate the shared default object. */
export function cloneConfig(config: DesignConfig): DesignConfig {
  return JSON.parse(JSON.stringify(config)) as DesignConfig;
}
