import { describe, it, expect } from "vitest";
import {
  generateAllMarkdown,
  generateDesignTokens,
  generateDesignGuidelines,
  generateComponentPatterns,
  generateAiRules,
  generateAiEntrypoint,
} from "./index";
import { defaultConfig, cloneConfig } from "@/lib/config/defaults";

const DATE = "2026-05-31T00:00:00.000Z";
const opts = { date: DATE };

describe("generateAllMarkdown", () => {
  it("produces exactly 5 files in stable order", () => {
    const files = generateAllMarkdown(defaultConfig, opts);
    expect(files.map((f) => f.filename)).toEqual([
      "theme-config-system-design-tokens.md",
      "theme-config-system-design-guidelines.md",
      "theme-config-system-component-patterns.md",
      "theme-config-system-ai-rules.md",
      "theme-config-system-ai-entrypoint.md",
    ]);
  });

  it("derives file names from the project name", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.name = "My Cool Brand!";
    const files = generateAllMarkdown(c, opts);
    expect(files[0].filename).toBe("my-cool-brand-design-tokens.md");
  });

  it("stamps every file with the same version + timestamp header", () => {
    const files = generateAllMarkdown(defaultConfig, opts);
    for (const f of files) {
      expect(f.content).toContain(
        `<!-- Generated by Theme Config · v${defaultConfig.meta.version} · ${DATE} -->`,
      );
    }
  });

  it("uses one shared timestamp even when none is passed", () => {
    const files = generateAllMarkdown(defaultConfig);
    const stamps = files.map((f) => f.content.match(/· (\S+) -->/)![1]);
    expect(new Set(stamps).size).toBe(1);
  });
});

describe("design-tokens.md", () => {
  const md = generateDesignTokens(defaultConfig, opts);

  it("has all required sections", () => {
    for (const section of [
      "## Colors",
      "## Typography",
      "## Spacing",
      "## Radius",
      "## Borders",
      "## Elevation",
      "## Animation",
      "## JSON export",
      "## CSS Variables",
    ]) {
      expect(md).toContain(section);
    }
  });

  it("contains the primary base hex and a 600 scale token", () => {
    expect(md).toContain(defaultConfig.theme.colors.primary);
    expect(md).toContain("primary-600");
  });

  it("embeds valid JSON in the JSON export block", () => {
    const match = md.match(/## JSON export\n\n```json\n([\s\S]*?)\n```/);
    expect(match).not.toBeNull();
    expect(() => JSON.parse(match![1])).not.toThrow();
  });

  it("emits a dark theme block when mode is both", () => {
    const c = cloneConfig(defaultConfig);
    c.theme.mode = "both";
    const out = generateDesignTokens(c, opts);
    expect(out).toContain('[data-theme="dark"]');
  });

  it("includes an Opacity section and opacity CSS variables", () => {
    expect(md).toContain("## Opacity");
    expect(md).toContain("opacity-primary-5");
    expect(md).toContain("--opacity-black-7:");
  });
});

describe("shadcn & antd stacks", () => {
  it("entrypoint emits shadcn globals.css adapter for shadcn component lib", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.componentLib = "shadcn";
    const md = generateAiEntrypoint(c, opts);
    expect(md).toContain("shadcn");
    expect(md).toContain("--primary:");
    expect(md).not.toContain("tailwind.config.ts"); // uses shadcn's own config
  });

  it("entrypoint emits antd ConfigProvider theme for antd component lib", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.componentLib = "antd";
    const md = generateAiEntrypoint(c, opts);
    expect(md).toContain("ConfigProvider");
    expect(md).toContain("colorPrimary");
  });

  it("component-patterns uses antd imports for antd component lib", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.componentLib = "antd";
    const md = generateComponentPatterns(c, opts);
    expect(md).toContain('from "antd"');
    expect(md).toContain("ConfigProvider");
  });

  it("component-patterns uses shadcn imports for shadcn component lib", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.componentLib = "shadcn";
    const md = generateComponentPatterns(c, opts);
    expect(md).toContain("@/components/ui/button");
  });

  it("ignores component lib for non-React stacks", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.targetStack = "html-css";
    c.meta.componentLib = "shadcn"; // should be ignored — html-css can't use shadcn
    const md = generateComponentPatterns(c, opts);
    expect(md).not.toContain("@/components/ui/button");
    expect(md).toContain("<style>");
  });
});

describe("reference-rule enrichment", () => {
  it("ai-rules adds anti-patterns, no-invented-tokens, opacity & asset rules", () => {
    const md = generateAiRules(defaultConfig, opts);
    expect(md).toContain("## Anti-patterns");
    expect(md).toContain("MUST NOT invent missing tokens");
    expect(md).toContain("opacity");
    expect(md.toLowerCase()).toContain("brand asset");
  });

  it("design-guidelines adds layout rules + deepen-in-scale hover", () => {
    const md = generateDesignGuidelines(defaultConfig, opts);
    expect(md).toContain("## Layout");
    expect(md).toContain("deepen within the same scale");
  });

  it("component-patterns documents loading + status/read-only + board cells", () => {
    const md = generateComponentPatterns(defaultConfig, opts);
    expect(md).toContain("loading");
    expect(md).toContain("read-only");
    expect(md).toContain("board cell");
  });
});

describe("design-guidelines.md", () => {
  it("reflects the chosen accessibility level", () => {
    const c = cloneConfig(defaultConfig);
    c.aiRules.accessibility = "AAA";
    const md = generateDesignGuidelines(c, opts);
    expect(md).toContain("7:1");
  });

  it("notes when motion is disabled", () => {
    const c = cloneConfig(defaultConfig);
    c.animation.enabled = false;
    const md = generateDesignGuidelines(c, opts);
    expect(md.toLowerCase()).toContain("disabled");
  });
});

describe("component-patterns.md", () => {
  it("emits tsx for react-tailwind and html for html-css", () => {
    const react = generateComponentPatterns(defaultConfig, opts);
    expect(react).toContain("```tsx");

    const c = cloneConfig(defaultConfig);
    c.meta.targetStack = "html-css";
    const html = generateComponentPatterns(c, opts);
    expect(html).toContain("```html");
  });

  it("references tokens and never hard-codes the primary hex in samples", () => {
    const md = generateComponentPatterns(defaultConfig, opts);
    expect(md).toContain("var(--color-primary-600)");
  });

  it("includes optional components only when enabled", () => {
    const c = cloneConfig(defaultConfig);
    c.components.badge.enabled = false;
    c.components.modal.enabled = false;
    c.components.table.enabled = false;
    const md = generateComponentPatterns(c, opts);
    expect(md).not.toContain("## Badge");
    expect(md).not.toContain("## Modal");
    expect(md).not.toContain("## Table");
  });
});

describe("ai-rules.md", () => {
  it("includes custom rules and a checklist", () => {
    const c = cloneConfig(defaultConfig);
    c.aiRules.customRules = ["Always use lucide-react for icons"];
    const md = generateAiRules(c, opts);
    expect(md).toContain("Always use lucide-react for icons");
    expect(md).toContain("## Checklist");
  });

  it("forbids hard-coded values when enforceTokensOnly is on", () => {
    const md = generateAiRules(defaultConfig, opts);
    expect(md).toContain("MUST NOT");
  });
});

describe("interactive states", () => {
  it("design-guidelines documents the configured hover effect", () => {
    const c = cloneConfig(defaultConfig);
    c.interactions.hover = "lift";
    const md = generateDesignGuidelines(c, opts);
    expect(md).toContain("## Interactive states");
    expect(md).toContain("Lift");
  });

  it("component-patterns emits a reusable interactive class string for tailwind", () => {
    const md = generateComponentPatterns(defaultConfig, opts);
    expect(md).toContain("## Interactive states");
    expect(md).toContain("const interactive =");
    expect(md).toContain("focus-visible:outline");
  });

  it("component-patterns emits CSS interactive states for html-css", () => {
    const c = cloneConfig(defaultConfig);
    c.meta.targetStack = "html-css";
    const md = generateComponentPatterns(c, opts);
    expect(md).toContain(".interactive:hover");
    expect(md).toContain(":focus-visible");
  });

  it("ai-rules requires hover/active/disabled states", () => {
    const md = generateAiRules(defaultConfig, opts);
    expect(md).toContain("## Interactive states");
    expect(md).toContain("Hover / active / disabled states defined");
  });

  it("respects disabled focus ring / press feedback", () => {
    const c = cloneConfig(defaultConfig);
    c.interactions.focusRing = false;
    c.interactions.pressFeedback = false;
    const md = generateDesignGuidelines(c, opts);
    expect(md.toLowerCase()).toContain("focus ring disabled");
  });
});

describe("ai-entrypoint.md", () => {
  const md = generateAiEntrypoint(defaultConfig, opts);

  it("embeds css variables, a starter prompt, and links companion files", () => {
    expect(md).toContain(":root {");
    expect(md).toContain("Starter prompt");
    expect(md).toContain("design-tokens.md");
    expect(md).toContain("ai-rules.md");
  });

  it("includes a tailwind config snippet for tailwind stacks only", () => {
    expect(md).toContain("tailwind.config.ts");
    const c = cloneConfig(defaultConfig);
    c.meta.targetStack = "html-css";
    expect(generateAiEntrypoint(c, opts)).not.toContain("tailwind.config.ts");
  });
});
