import type { DesignConfig } from "@/lib/config/types";

export interface GenerateOptions {
  /** ISO date string stamped into the header. Pass explicitly for deterministic output/tests. */
  date?: string;
}

/** Traceability header required on every generated file. */
export function header(config: DesignConfig, opts?: GenerateOptions): string {
  const date = opts?.date ?? new Date().toISOString();
  return `<!-- Generated by DesignSync Studio · v${config.meta.version} · ${date} -->`;
}

/** Render a GitHub-flavoured markdown table. */
export function table(headers: string[], rows: (string | number)[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows
    .map((r) => `| ${r.map((cell) => String(cell)).join(" | ")} |`)
    .join("\n");
  return [head, sep, body].join("\n");
}

/** Fenced code block. */
export function codeBlock(lang: string, content: string): string {
  return "```" + lang + "\n" + content + "\n```";
}
